### ISSUE TITLE
Sqlite error: no such table keyword

### ISSUE THREAD

**Issue by MyWay** [towfiqi/serpbear#161]
Hi, fresh docker-compose install, I'm getting:

```
Sequelize CLI [Node: 20.11.0, CLI: 6.6.2, ORM: 6.36.0]

Loaded configuration file "database/config.js".
Using environment "production".
== 1707068556345-add-new-keyword-fields: migrating =======


ERROR: SQLITE_ERROR: no such table: keyword
```

docker-compose.yml
```
version: '3.8' 

services:
  serpbear:
    image: towfiqi/serpbear
    container_name: serpbear 
    restart: always
    volumes: 
      - serpbear_data:/app/data
    ports:
      - 6000:3000
    environment:
      USER: "${USER}"
      PASSWORD: "${PASSWORD}"
      SECRET: "${SECRET}"
      APIKEY: "${APIKEY}"
      NEXT_PUBLIC_APP_URL: "https://myurl"
      SEARCH_CONSOLE_CLIENT_EMAIL: "${SEARCH_CONSOLE_CLIENT_EMAIL}"
      SEARCH_CONSOLE_PRIVATE_KEY: "${SEARCH_CONSOLE_PRIVATE_KEY}"
```
