### ISSUE TITLE
Instructions for deploying SerpBear to FlashPanel

### ISSUE THREAD

**Issue by nguyentranchung** [towfiqi/serpbear#234]
# Deploy SerpBear

1. Install the `docker` application in the server's applications tab

2. Create a proxy website port to port `4444` (this port is up to you to decide)

<img width="797" alt="Screenshot 2024-07-10 at 13 32 31" src="https://github.com/towfiqi/serpbear/assets/9611224/1da4b085-d980-4cde-a309-f6132653995c">

Proceed with SSL installation for this website

3. Open the file manager for the server (not the site)

Proceed to create the file `serpbear/docker-compose.yaml`

<img width="1329" alt="Screenshot 2024-07-10 at 13 35 10" src="https://github.com/towfiqi/serpbear/assets/9611224/de2835ff-8068-46f7-ae20-5cc4e03c0d01">

4. Open the newly created `docker-compose.yaml` file

<img width="1087" alt="Screenshot 2024-07-10 at 13 38 12" src="https://github.com/towfiqi/serpbear/assets/9611224/46473d76-2042-4c62-acc4-d8d360c87894">

5. Enter content for the `docker-compose.yaml` file

```yaml
version: "3.8"

services:
    app:
        image: towfiqi/serpbear
        restart: unless-stopped
        ports:
            - 4444:3000 # [!code warning]
        environment:
            - USER=admin # [!code warning]
            - PASSWORD=0123456789 # [!code warning]
            - SECRET=4715aed3216f7b0a38e6b534a958362654e96d10fbc04700770d572af3dce43625dd # [!code warning]
            - APIKEY=5saedXklbslhnapihe2pihp3pih4fdnakhjwq5 # [!code warning]
            - SESSION_DURATION=24
            - NEXT_PUBLIC_APP_URL=https://your-domain.com # [!code warning]
        volumes:
            - serpbear_appdata:/app/data
networks:
    my-network:
        driver: bridge
volumes:
    serpbear_appdata:
```

Note for configuring the following colored lines:

-   `4444:3000`: `3000` is fixed and you should not change it, `4444` is the port of the serpbear website that you decided to create in step 2
-   `USER`: The username you want to use to log in to the application. for example: `admin`
-   `PASSWORD`: The password you want to use to log in to the application. For example: `0123456789`
-   `SECRET`: The secret key will be used to encrypt 3rd party API keys and passwords. e.g. `4715aed3216f7b0a38e6b534a958362654e96d10fbc04700770d572af3dce43625dd`
-   `APIKEY`: The API key that will be used to access the application's API. for example: `5saedXklbslhnapihe2pihp3pih4fdnakhjwq5`
-   `SESSION_DUration`: Duration (in hours) of the user's login session. e.g. `24`
-   `NEXT_PUBLIC_APP_URL`: The URL where your app is stored and accessible. for example: `http://123.123.123.123:4444` or `https://your-domain.com`

6. Launch the application

<img width="788" alt="Screenshot 2024-07-10 at 13 58 48" src="https://github.com/towfiqi/serpbear/assets/9611224/07caf80b-5cb8-4699-b75e-1e3a2e7821b4">

Open the terminal server and run the following command:

```bash
cd /root/serpbear
docker compose up -d
```
