### ISSUE TITLE
"exec /usr/local/bin/docker-entrypoint.sh: exec format error" while running on Raspberry Pi 4

### ISSUE THREAD

**Issue by maxdelia** [towfiqi/serpbear#42]
Hello and thank you for this amazing project!

I have the following error running the docker image on a Raspberry Pi 4:

```
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

I suspect it may be caused by the OS/ARCH settings the docker image is build with.
Could You please provide a docker image build for **linux/arm/v7** also? Many thanks!

**Comment by MarseyLivesMatter** [comment]
If you're using the 64 bit version of the Raspberry Pi OS I've built an ARM64 image which you can find here: https://hub.docker.com/r/marseythecat/serpbear

**Comment by maxdelia** [comment]
Thanks for your help @MarseyLivesMatter , I really appreciate it!
Having an official image will increase the usage of this beautiful product IMHO, what do You think @towfiqi ?

**Comment by bilyboy785** [comment]
Hi !

@towfiqi, you could use Github action to automate docker image Build with multi arch with something like in `.github/workflows/build-push-multiarch-image.yml` : 

```
name: Build & Push Docker Image

env:
  DOCKERHUB_USERNAME: towfiqi
  DOCKERHUB_IMAGE: serpbear

on:
  push:
    tags: [ '*' ]
    branches: [ "main" ]
  # schedule:
  #   - cron: "30 5 * * *"


jobs:
  build_push:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{env.DOCKERHUB_USERNAME}}/${{env.DOCKERHUB_IMAGE}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{env.DOCKERHUB_USERNAME}}/${{env.DOCKERHUB_IMAGE}}:latest
```
